### ISSUE TITLE
StrictMode Closeables

### ISSUE THREAD

**Issue by chrisjenx** [dmytrodanylyk/video-crop#4]
You seem to leak a lot of resources.

``` bash
09-16 16:10:35.809  10955-10967/com.justyoyo.staging.debug E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'release' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at android.view.Surface.setNativeObjectLocked(Surface.java:397)
            at android.view.Surface.<init>(Surface.java:128)
            at com.justyoyo.ui.views.video.TextureVideoView.onSurfaceTextureAvailable(TextureVideoView.java:359)
            at android.view.TextureView.getHardwareLayer(TextureView.java:385)
            at android.view.View.getDisplayList(View.java:13353)
            at android.view.View.getDisplayList(View.java:13429)
            at android.view.View.draw(View.java:14207)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13382)
            at android.view.View.getDisplayList(View.java:13429)
            at android.view.View.draw(View.java:14207)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13382)
            at android.view.View.getDisplayList(View.java:13429)
            at android.view.View.draw(View.java:14207)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13382)
            at android.view.View.getDisplayList(View.java:13429)
            at android.view.View.draw(View.java:14207)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.draw(View.java:14493)
            at android.widget.FrameLayout.draw(FrameLayout.java:472)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java)
            at android.view.View.getDisplayList(View.java:13387)
            at android.view.View.getDisplayList(View.java:13429)
            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2488)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2343)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1935)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1025)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5808)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:595)
            at android.view.Choreographer.doFrame(Choreographer.java:555)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5171)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
```

**Comment by jzeferino** [comment]
@chrisjenx what are the fixes you made?

**Comment by chrisjenx** [comment]
Based on the timestamp, in a test app that died many years ago.
